### ISSUE TITLE
How to suggest corrections to the alpinejs.dev docs?

### ISSUE THREAD

**Issue by arcanemachine** [alpinejs/alpine-next#15]
Not sure where to report any typos for the new docs...

The [x-for](https://alpinejs.dev/directives/for) page contains the word "specificy" (should be 'specify').

The [Reactivity](https://www.alpinejs.dev/advanced/reactivity) page contains the word "firt" (should be 'first'). It also contains the word "paradaigm" (should be 'paradigm').

The [Extending](https://www.alpinejs.dev/advanced/extending) page contains the word "retreiving" (should be 'retrieving'). It also contains a couple instances of the word "dependancies" which should be 'dependencies' (I would suggest Ctrl+F'ing all the docs for 'dependanc' since it seems like it might be habitual).

The [x-effect](https://www.alpinejs.dev/directives/effect) page contains the same typo noted above.

The [Alpine 101](https://www.alpinejs.dev/alpine-101) page contains the phrase "self-explanitory", which should be "self-explanatory".

**Comment by marksalmon** [comment]
The docs are part of this repo in packages/docs so I think you can PR here

**Comment by arcanemachine** [comment]
Ah, so they are.

Thank you, I'll fix up a PR.
